import type { Metadata } from "next";
import "./globals.css";

import { AuthProvider } from "./context/wAuthContext";
import { QueryProvider } from "./lib/react-query/QueryProvider";

export const metadata: Metadata = {
  title: "Social Media App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <QueryProvider>
        <html lang="en">
          <body
            className={``}
          >
            {children}
          </body>
        </html>
      </QueryProvider>
    </AuthProvider>
  );
}
